CREATE TABLE public.tenants
(
  id         UUID PRIMARY KEY         DEFAULT gen_random_uuid(),
  name       VARCHAR(255) UNIQUE NOT NULL,
  is_deleted BOOLEAN                  DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
